export enum NAVIGATION_KEYS {
	LOGIN = 'LOGIN',
	CHATS_STACK = 'CHATS_STACK',
	ADD_FRIENDS_STACK = 'ADD_FRIENDS_STACK',
	FRIENDS_STACK = 'FRIENDS_STACK',
	SETTINGS_STACK = 'SETTINGS_STACK',
	CHATS = 'CHATS',
	ADD_FRIENDS = 'ADD_FRIENDS',
	FRIENDS = 'FRIENDS',
	SETTINGS = 'SETTINGS',
}

export type RootStackParamList = {
	[NAVIGATION_KEYS.LOGIN]: undefined;
	[NAVIGATION_KEYS.CHATS]: undefined;
	[NAVIGATION_KEYS.ADD_FRIENDS]: undefined;
	[NAVIGATION_KEYS.FRIENDS]: undefined;
	[NAVIGATION_KEYS.SETTINGS]: undefined;
};
